### ISSUE TITLE
Display Timezone with Offset

### ISSUE THREAD

**Issue by aljawaid** [dexise/jQuery-Analog-Clock#3]
Hello, this is a great simple clock.

Any chance we can show the timezone as a label somehow?

I have set the timezone in the script but how to show it also?

Also, can we display the clock in digital format or as text so we can style it ourselves in CSS?

Your reply would be appreciated.

**Comment by uncox** [comment]
> Hello, this is a great simple clock.

Thanks for your Feedback

> Any chance we can show the timezone as a label somehow?

Currently No. It's possible and straightforward if you are familiar with javascript coding.

> I have set the timezone in the script but how to show it also?

It's not supported out of the box; you can custom develop this plugin to support it.

> Also, can we display the clock in digital format or as text so we can style it ourselves in CSS?

This is just an Analog Clock and the settings are not supported for digital viewing.

Your reply would be appreciated.
